name: Ejecutar bot cada hora

on:
  schedule:
    # Esto indica que se ejecute cada hora (en el minuto 0 de cada hora)
    - cron: '0 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar bot
        run: |
          python main.py
